//! crusty_os kernel library crate.
//!
//! Exposes the kernel's hardware-facing subsystems (GDT, IDT, interrupt
//! controllers, heap allocator, VGA text buffer) and re-exports the shared
//! test infrastructure that integration tests depend on.
//!
//! # Architecture
//!
//! ```text
//! crusty_os  ──depends on──▶  framework  (output + test runner, no hardware)
//!    │        ──depends on──▶  platform   (UART, QEMU exit, x86_64 I/O)
//!    │        ──depends on──▶  barnacle   (Multiboot2 boot — default)
//!    │        ──depends on──▶  abalone    (allocator implementations)
//!    │
//!    └── integration tests use crusty_os::test_runner (wraps framework::runner
//!                              + calls platform::exit_success on completion)
//! ```
//!
//! # Test infrastructure
//!
//! Lib-level tests (`cargo test -p crusty_os --lib`) use the entry point
//! `test_kernel_main` below, generated by `barnacle::entry_point!`.
//! Integration tests (in `tests/`) set `#![test_runner(crusty_os::test_runner)]`
//! and call `unsafe { platform::init() }` at their own entry point.
//!
//! [`test_panic_handler`] is provided for integration tests that use
//! `harness = false` so they can still report failures via serial.

#![no_std]
#![cfg_attr(test, no_main)]
#![feature(custom_test_frameworks)]
#![test_runner(framework::runner)]
#![reexport_test_harness_main = "test_main"]
#![feature(abi_x86_interrupt)]

use core::panic::PanicInfo;

pub mod serial;
pub mod vga_buffer;
pub mod interrupts;
pub mod gdt;
pub mod allocator;

extern crate alloc;

// ── Re-export KernelBootInfo for integration tests ────────────────────────────

pub use framework::KernelBootInfo;

// ── Allocator initialisation (multiboot2 + limine paths) ─────────────────────

/// Populate the buddy allocator from usable memory regions and carve a TLSF pool.
///
/// # Safety
/// Must be called exactly once, before any heap allocation.
#[cfg(any(feature = "boot-multiboot2", feature = "boot-limine"))]
pub unsafe fn allocator_init(info: &framework::KernelBootInfo) {
    use crate::allocator::buddy;
    use framework::{MemoryRegionKind, PAGE_SIZE};

    {
        let mut b = buddy::BUDDY.lock();
        for region in info.regions_of_kind(MemoryRegionKind::Usable) {
            // Multiboot2: only physical [HEAP_START_PHYS, 2 MB) is HHDM-mapped
            // at boot. Regions outside this window are silently skipped.
            #[cfg(feature = "boot-multiboot2")]
            {
                const HEAP_START_PHYS: u64 = 0x16_0000;
                const BOOT_MAPPED_PHYS: u64 = 2 * 1024 * 1024;

                let clamped_base = region.base.max(HEAP_START_PHYS);
                let clamped_end  = (region.base + region.length).min(BOOT_MAPPED_PHYS);
                if clamped_end <= clamped_base { continue; }

                let virt_base  = info.hhdm_offset + clamped_base as usize;
                let page_count = ((clamped_end - clamped_base) as usize) / PAGE_SIZE;
                if page_count > 0 {
                    b.add_region(virt_base, page_count);
                }
            }

            // Limine: all usable RAM is HHDM-mapped before _start is called.
            #[cfg(feature = "boot-limine")]
            {
                let page_base  = (region.base as usize + PAGE_SIZE - 1) & !(PAGE_SIZE - 1);
                let page_end   = (region.base + region.length) as usize & !(PAGE_SIZE - 1);
                if page_end <= page_base { continue; }
                let virt_base  = info.hhdm_offset + page_base;
                let page_count = (page_end - page_base) / PAGE_SIZE;
                if page_count > 0 {
                    b.add_region(virt_base, page_count);
                }
            }
        }
    }

    // Carve a TLSF pool from buddy pages and initialise the global allocator.
    // Multiboot2: order 6 = 64 pages = 256 KiB (fits in the ~640 KiB window).
    // Limine:     order 8 = 256 pages = 1 MiB  (ample RAM available).
    #[cfg(feature = "boot-multiboot2")]
    crate::allocator::TLSF.init(6);

    #[cfg(feature = "boot-limine")]
    crate::allocator::TLSF.init(8);
}

// ── Re-exports for integration tests ─────────────────────────────────────────

/// Re-export so integration tests can write `use crusty_os::Testable` without
/// knowing about the `framework` crate directly.
pub use framework::Testable;

/// Test runner used by all integration tests (`#![test_runner(crusty_os::test_runner)]`).
///
/// Delegates to [`framework::runner`] for output, then calls
/// [`platform::exit_success`] so QEMU exits with the success code after all
/// tests pass.  If any test panics the `#[panic_handler]` calls
/// [`test_panic_handler`] instead, exiting with the failure code.
pub fn test_runner(tests: &[&dyn framework::Testable]) {
    framework::runner(tests);
    platform::exit_success();
}

/// Re-export so integration tests can use `QemuExitCode` without a direct
/// `platform` dependency.
pub use platform::QemuExitCode;

/// Backwards-compatible wrapper: integration tests expect a `()` return type,
/// but [`platform::exit_qemu`] returns `!`.
pub fn exit_qemu(code: QemuExitCode) {
    platform::exit_qemu(code);
}

/// Panic handler for integration tests that use `harness = false`.
///
/// Prints `[failed]` and the panic info over serial, then exits QEMU with
/// the failure code.  Wire up via `#[panic_handler]` in the test file.
pub fn test_panic_handler(info: &PanicInfo) -> ! {
    use framework::kprintln;
    kprintln!("[failed]\n");
    kprintln!("Error: {}\n", info);
    platform::exit_failure()
}

// ── Panic handler (lib-test builds only) ─────────────────────────────────────

#[cfg(test)]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    test_panic_handler(info)
}

// ── Lib-test entry point (multiboot2 / barnacle) ──────────────────────────────

#[cfg(all(test, feature = "boot-multiboot2"))]
barnacle::entry_point!(test_kernel_main);

/// Entry point for `cargo test -p crusty_os --lib`.
///
/// Initialises the heap so allocator unit tests can run, then loads GDT/IDT
/// before handing off to the test harness.
#[cfg(all(test, feature = "boot-multiboot2"))]
fn test_kernel_main(kbi: &'static framework::KernelBootInfo) -> ! {
    unsafe { platform::init(); }
    unsafe { allocator_init(kbi); }
    init();
    test_main();
    platform::exit_success()
}

// ── Kernel subsystem init ─────────────────────────────────────────────────────

/// Initialize core x86_64 kernel subsystems.
///
/// Sets up the GDT, IDT, PIC interrupt controllers, and enables hardware
/// interrupts.  Must be called before any code that relies on interrupts or
/// hardware exception handlers (e.g. page fault, double fault).
pub fn init() {
    gdt::init();
    interrupts::init();
    x86_64::instructions::interrupts::enable();
}

/// Halt the CPU in a loop, yielding on each iteration.
pub fn hlt_loop() -> ! {
    loop {
        x86_64::instructions::hlt();
    }
}
