//! crusty_os kernel entry point.
//!
//! Build variants:
//!   cargo build -p crusty_os                          → Multiboot2 / GRUB via barnacle (default)
//!   cargo build -p crusty_os --no-default-features \
//!     --features boot-limine                          → Limine bootloader

#![no_std]
#![no_main]
#![feature(custom_test_frameworks)]
#![test_runner(crusty_os::test_runner)]
#![reexport_test_harness_main = "test_main"]

use core::panic::PanicInfo;
use crusty_os::println;

extern crate alloc;

// ── Boot module (limine path only — multiboot2 entry is via barnacle below) ───

#[cfg(any(feature = "boot-multiboot2", feature = "boot-limine"))]
mod boot;

// ── Multiboot2 entry point (generated by barnacle) ───────────────────────────

#[cfg(feature = "boot-multiboot2")]
barnacle::entry_point!(multiboot2_start);

#[cfg(feature = "boot-multiboot2")]
fn multiboot2_start(kbi: &'static framework::KernelBootInfo) -> ! {
    unsafe { crusty_os::allocator_init(kbi); }
    kernel_main_post_heap()
}

// Limine: _start is defined in boot/limine.rs (#[no_mangle]).

// ── Panic handlers ───────────────────────────────────────────────────────────

#[cfg(not(test))]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    use framework::kprintln;
    kprintln!("{}", info);
    platform::exit_failure()
}

#[cfg(test)]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    crusty_os::test_panic_handler(info)
}

// ── Post-heap kernel main (multiboot2 + limine paths) ────────────────────────

#[cfg(any(feature = "boot-multiboot2", feature = "boot-limine"))]
pub fn kernel_main_post_heap() -> ! {
    use alloc::{boxed::Box, rc::Rc, vec, vec::Vec};

    unsafe { platform::init(); }

    println!("Hello from kernel_main_post_heap!");

    crusty_os::init();

    let heap_value = Box::new(41);
    println!("heap_value at {:p}", heap_value);

    let mut vec = Vec::new();
    for i in 0..500 { vec.push(i); }
    println!("vec at {:p}", vec.as_slice());

    let reference_counted = Rc::new(vec![1, 2, 3]);
    let cloned_reference  = reference_counted.clone();
    println!("current reference count is {}", Rc::strong_count(&cloned_reference));
    core::mem::drop(reference_counted);
    println!("current reference count is {}", Rc::strong_count(&cloned_reference));

    println!("It did not crash!");

    crusty_os::hlt_loop()
}
