//! crusty_os kernel entry point.
//!
//! Build variants:
//!   cargo build -p crusty_os                          → legacy bootloader (default)
//!   cargo build -p crusty_os --no-default-features \
//!     --features boot-multiboot2                      → Multiboot2 / GRUB via barnacle
//!   cargo build -p crusty_os --no-default-features \
//!     --features boot-limine                          → Limine bootloader

#![no_std]
#![no_main]
#![feature(custom_test_frameworks)]
#![test_runner(crusty_os::test_runner)]
#![reexport_test_harness_main = "test_main"]

use core::panic::PanicInfo;
use crusty_os::println;

extern crate alloc;

// ── Boot module (limine path only — multiboot2 entry is via barnacle below) ───

#[cfg(any(feature = "boot-multiboot2", feature = "boot-limine"))]
mod boot;

// ── Multiboot2 entry point (generated by barnacle) ───────────────────────────

#[cfg(feature = "boot-multiboot2")]
barnacle::entry_point!(multiboot2_start);

#[cfg(feature = "boot-multiboot2")]
fn multiboot2_start(kbi: &'static framework::KernelBootInfo) -> ! {
    unsafe { allocator_init(kbi); }
    kernel_main_post_heap()
}

// Limine: _start is defined in boot/limine.rs (#[no_mangle]).
// Legacy: kmain is defined below.

// ── Panic handlers ───────────────────────────────────────────────────────────

#[cfg(not(test))]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    use framework::kprintln;
    kprintln!("{}", info);
    platform::exit_failure()
}

#[cfg(test)]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    crusty_os::test_panic_handler(info)
}

// ── Allocator initialisation (multiboot2 + limine paths) ─────────────────────

/// Populate the buddy allocator from usable memory regions and carve a TLSF pool.
///
/// # Safety
/// Must be called exactly once, before any heap allocation.
#[cfg(any(feature = "boot-multiboot2", feature = "boot-limine"))]
pub unsafe fn allocator_init(info: &framework::KernelBootInfo) {
    use crusty_os::allocator::buddy;
    use framework::{MemoryRegionKind, PAGE_SIZE};

    {
        let mut b = buddy::BUDDY.lock();
        for region in info.regions_of_kind(MemoryRegionKind::Usable) {
            // Multiboot2: only physical [HEAP_START_PHYS, 2 MB) is HHDM-mapped
            // at boot. Regions outside this window are silently skipped.
            #[cfg(feature = "boot-multiboot2")]
            {
                const HEAP_START_PHYS: u64 = 0x16_0000;
                const BOOT_MAPPED_PHYS: u64 = 2 * 1024 * 1024;

                let clamped_base = region.base.max(HEAP_START_PHYS);
                let clamped_end  = (region.base + region.length).min(BOOT_MAPPED_PHYS);
                if clamped_end <= clamped_base { continue; }

                let virt_base  = info.hhdm_offset + clamped_base as usize;
                let page_count = ((clamped_end - clamped_base) as usize) / PAGE_SIZE;
                if page_count > 0 {
                    b.add_region(virt_base, page_count);
                }
            }

            // Limine: all usable RAM is HHDM-mapped before _start is called.
            #[cfg(feature = "boot-limine")]
            {
                let page_base  = (region.base as usize + PAGE_SIZE - 1) & !(PAGE_SIZE - 1);
                let page_end   = (region.base + region.length) as usize & !(PAGE_SIZE - 1);
                if page_end <= page_base { continue; }
                let virt_base  = info.hhdm_offset + page_base;
                let page_count = (page_end - page_base) / PAGE_SIZE;
                if page_count > 0 {
                    b.add_region(virt_base, page_count);
                }
            }
        }
    }

    // Carve a TLSF pool from buddy pages and initialise the global allocator.
    // Multiboot2: order 6 = 64 pages = 256 KiB (fits in the ~640 KiB window).
    // Limine:     order 8 = 256 pages = 1 MiB  (ample RAM available).
    #[cfg(feature = "boot-multiboot2")]
    crusty_os::allocator::TLSF.init(6);

    #[cfg(feature = "boot-limine")]
    crusty_os::allocator::TLSF.init(8);
}

// ── Post-heap kernel main (multiboot2 + limine paths) ────────────────────────

#[cfg(any(feature = "boot-multiboot2", feature = "boot-limine"))]
pub fn kernel_main_post_heap() -> ! {
    use alloc::{boxed::Box, rc::Rc, vec, vec::Vec};

    unsafe { platform::init(); }

    println!("Hello from kernel_main_post_heap!");

    crusty_os::init();

    // Heap smoke tests.
    let heap_value = Box::new(41);
    println!("heap_value at {:p}", heap_value);

    let mut vec = Vec::new();
    for i in 0..500 { vec.push(i); }
    println!("vec at {:p}", vec.as_slice());

    let reference_counted = Rc::new(vec![1, 2, 3]);
    let cloned_reference  = reference_counted.clone();
    println!("current reference count is {}", Rc::strong_count(&cloned_reference));
    core::mem::drop(reference_counted);
    println!("current reference count is {}", Rc::strong_count(&cloned_reference));

    println!("It did not crash!");

    crusty_os::hlt_loop()
}

// ── Legacy bootloader path ────────────────────────────────────────────────────

#[cfg(feature = "use-bootloader")]
bootloader::entry_point!(kmain);

#[cfg(feature = "use-bootloader")]
fn kmain(boot_info: &'static bootloader::BootInfo) -> ! {
    use alloc::{boxed::Box, rc::Rc, vec, vec::Vec};
    use crusty_os::{allocator, memory};
    use crusty_os::memory::BootInfoFrameAllocator;
    use x86_64::VirtAddr;

    unsafe { platform::init(); }

    println!("Hello World{}", "!");

    crusty_os::init();

    let phys_mem_offset = VirtAddr::new(boot_info.physical_memory_offset);
    let mut mapper = unsafe { memory::init(phys_mem_offset) };
    let mut frame_allocator = unsafe { BootInfoFrameAllocator::init(&boot_info.memory_map) };

    allocator::init_heap(&mut mapper, &mut frame_allocator).expect("heap initialization failed");

    let heap_value = Box::new(41);
    println!("heap_value at {:p}", heap_value);

    let mut vec = Vec::new();
    for i in 0..500 { vec.push(i); }
    println!("vec at {:p}", vec.as_slice());

    let reference_counted = Rc::new(vec![1, 2, 3]);
    let cloned_reference  = reference_counted.clone();
    println!("current reference count is {}", Rc::strong_count(&cloned_reference));
    core::mem::drop(reference_counted);
    println!("current reference count is {}", Rc::strong_count(&cloned_reference));

    println!("It did not crash!");

    #[cfg(test)]
    test_main();

    crusty_os::hlt_loop()
}
